name: Cypress Tests

on: [push]

jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
       with:
        working-directory: frontend
     - name: Run cypress test
       uses: cypress-io/github-action@v2
       with:
         working-directory: frontend
         build: npm run build
         start: npm start
         browser: chrome