name: Cypress Tests

on: [push]

jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
 
     - name: Run cypress test
       uses: cypress-io/github-action@v3
       with:
         working-directory: frontend
         start: npm start
         build: npm build
         test:prod: npm run test:prod
         browser: chrome
