name: Cypress Tests
# Occurs when a branch is pushed
on: [push]

jobs:
  frontend:
    cypress-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Cypress run
          uses: cypress-io/github-action@v2
          with:
            build: npm run build
            start: npm start
            test:prod: npm run test:prod
